const listTimeZones = [
  {
    code: 'AU',
    countryName: 'Australia',
    timeZones: [
      'Australia/Lord_Howe',
      'Antarctica/Macquarie',
      'Australia/Hobart',
      'Australia/Currie',
      'Australia/Melbourne',
      'Australia/Sydney',
      'Australia/Broken_Hill',
      'Australia/Brisbane',
      'Australia/Lindeman',
      'Australia/Adelaide',
      'Australia/Darwin',
      'Australia/Perth',
      'Australia/Eucla',
    ],
  },
  {
    code: 'FR',
    countryName: 'France',
    timeZones: ['Europe/Paris'],
  },
  {
    code: 'DE',
    countryName: 'Germany',
    timeZones: ['Europe/Berlin', 'Europe/Busingen'],
  },
  {
    code: 'IN',
    countryName: 'India',
    timeZones: ['Asia/Kolkata'],
  },
  {
    code: 'GB',
    countryName: 'United Kingdom',
    timeZones: ['Europe/London'],
  },
  {
    code: 'US',
    countryName: 'United States',
    timeZones: [
      'America/New_York',
      'America/Detroit',
      'America/Kentucky/Louisville',
      'America/Kentucky/Monticello',
      'America/Indiana/Indianapolis',
      'America/Indiana/Vincennes',
      'America/Indiana/Winamac',
      'America/Indiana/Marengo',
      'America/Indiana/Petersburg',
      'America/Indiana/Vevay',
      'America/Chicago',
      'America/Indiana/Tell_City',
      'America/Indiana/Knox',
      'America/Menominee',
      'America/North_Dakota/Center',
      'America/North_Dakota/New_Salem',
      'America/North_Dakota/Beulah',
      'America/Denver',
      'America/Boise',
      'America/Phoenix',
      'America/Los_Angeles',
      'America/Anchorage',
      'America/Juneau',
      'America/Sitka',
      'America/Metlakatla',
      'America/Yakutat',
      'America/Nome',
      'America/Adak',
      'Pacific/Honolulu',
    ],
  },
];
